import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting LOGISTICS ONE Database Seeding (Indian Logistics Hub)...');

  // 1. Clean existing records
  await prisma.deliveryTimelineEvent.deleteMany({});
  await prisma.delivery.deleteMany({});
  await prisma.order.deleteMany({});
  await prisma.maintenanceLog.deleteMany({});
  await prisma.vehicle.deleteMany({});
  await prisma.driver.deleteMany({});
  await prisma.auditLog.deleteMany({});
  await prisma.systemSetting.deleteMany({});
  await prisma.user.deleteMany({});

  console.log('🧹 Cleaned existing database tables.');

  // 2. Create Users
  const adminPassword = await bcrypt.hash('admin123', 10);
  const dispatchPassword = await bcrypt.hash('dispatch123', 10);
  const opsPassword = await bcrypt.hash('ops123', 10);
  const driverPassword = await bcrypt.hash('driver123', 10);

  const adminUser = await prisma.user.create({
    data: {
      email: 'admin@fleetops.io',
      password: adminPassword,
      name: 'Rajesh Sharma',
      role: 'ADMIN',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    },
  });

  const dispatcherUser = await prisma.user.create({
    data: {
      email: 'dispatcher@fleetops.io',
      password: dispatchPassword,
      name: 'Priya Nair',
      role: 'DISPATCHER',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    },
  });

  const opsUser = await prisma.user.create({
    data: {
      email: 'ops@fleetops.io',
      password: opsPassword,
      name: 'Anand Verma',
      role: 'FLEET_MANAGER',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    },
  });

  const driverUser = await prisma.user.create({
    data: {
      email: 'driver@fleetops.io',
      password: driverPassword,
      name: 'Vikram Singh',
      role: 'DRIVER',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    },
  });

  console.log('👤 Created User accounts.');

  // 3. Create Drivers
  const driverData = [
    {
      userId: driverUser.id,
      code: 'DRV-101',
      firstName: 'Vikram',
      lastName: 'Singh',
      email: 'driver@fleetops.io',
      phone: '+91 98200 12345',
      licenseNumber: 'DL-MH-2022-0091234',
      licenseClass: 'HMV_HEAVY',
      licenseExpiry: new Date('2028-11-15'),
      status: 'ON_DELIVERY',
      rating: 4.95,
      totalDeliveries: 412,
      onTimeRatePercent: 98.8,
      emergencyContact: 'Sunita Singh (+91 98200 12349)',
    },
    {
      code: 'DRV-102',
      firstName: 'Ramesh',
      lastName: 'Gurjar',
      email: 'ramesh.g@fleetops.io',
      phone: '+91 98110 54321',
      licenseNumber: 'DL-GJ-2021-0033201',
      licenseClass: 'HMV_HEAVY',
      licenseExpiry: new Date('2027-08-20'),
      status: 'ON_DELIVERY',
      rating: 4.88,
      totalDeliveries: 320,
      onTimeRatePercent: 97.5,
      emergencyContact: 'Kavita Gurjar (+91 98110 54329)',
    },
    {
      code: 'DRV-103',
      firstName: 'Suresh',
      lastName: 'Kumar',
      email: 'suresh.k@fleetops.io',
      phone: '+91 98450 67890',
      licenseNumber: 'DL-KA-2020-0088410',
      licenseClass: 'HMV_HEAVY',
      licenseExpiry: new Date('2029-01-10'),
      status: 'ON_DELIVERY',
      rating: 4.98,
      totalDeliveries: 540,
      onTimeRatePercent: 99.2,
      emergencyContact: 'Lakshmi Kumar (+91 98450 67899)',
    },
    {
      code: 'DRV-104',
      firstName: 'Manoj',
      lastName: 'Yadav',
      email: 'manoj.y@fleetops.io',
      phone: '+91 97230 45678',
      licenseNumber: 'DL-DL-2021-0010928',
      licenseClass: 'HMV_HEAVY',
      licenseExpiry: new Date('2027-04-12'),
      status: 'ON_DELIVERY',
      rating: 4.82,
      totalDeliveries: 280,
      onTimeRatePercent: 96.1,
      emergencyContact: 'Pooja Yadav (+91 97230 45679)',
    },
    {
      code: 'DRV-105',
      firstName: 'Amit',
      lastName: 'Patel',
      email: 'amit.p@fleetops.io',
      phone: '+91 94440 98765',
      licenseNumber: 'DL-TN-2019-0067290',
      licenseClass: 'MMV_MEDIUM',
      licenseExpiry: new Date('2028-09-30'),
      status: 'AVAILABLE',
      rating: 4.92,
      totalDeliveries: 195,
      onTimeRatePercent: 98.0,
      emergencyContact: 'Dipti Patel (+91 94440 98769)',
    },
    {
      code: 'DRV-106',
      firstName: 'Sunil',
      lastName: 'Verma',
      email: 'sunil.v@fleetops.io',
      phone: '+91 98330 11223',
      licenseNumber: 'DL-MH-2023-0055120',
      licenseClass: 'LMV_TRANSPORT',
      licenseExpiry: new Date('2027-12-05'),
      status: 'AVAILABLE',
      rating: 4.79,
      totalDeliveries: 145,
      onTimeRatePercent: 95.8,
      emergencyContact: 'Anjali Verma (+91 98330 11229)',
    },
    {
      code: 'DRV-107',
      firstName: 'Pradeep',
      lastName: 'Nayak',
      email: 'pradeep.n@fleetops.io',
      phone: '+91 99000 33445',
      licenseNumber: 'DL-KA-2022-0044810',
      licenseClass: 'HMV_HEAVY',
      licenseExpiry: new Date('2029-06-18'),
      status: 'AVAILABLE',
      rating: 4.96,
      totalDeliveries: 380,
      onTimeRatePercent: 98.9,
      emergencyContact: 'Rekha Nayak (+91 99000 33449)',
    },
    {
      code: 'DRV-108',
      firstName: 'Gurpreet',
      lastName: 'Singh',
      email: 'gurpreet.s@fleetops.io',
      phone: '+91 98140 77889',
      licenseNumber: 'DL-PB-2020-0077291',
      licenseClass: 'MMV_MEDIUM',
      licenseExpiry: new Date('2028-03-22'),
      status: 'OFF_DUTY',
      rating: 4.85,
      totalDeliveries: 210,
      onTimeRatePercent: 96.9,
      emergencyContact: 'Harpreet Kaur (+91 98140 77880)',
    },
    {
      code: 'DRV-109',
      firstName: 'Deepak',
      lastName: 'Patil',
      email: 'deepak.p@fleetops.io',
      phone: '+91 98900 66554',
      licenseNumber: 'DL-MH-2021-0088192',
      licenseClass: 'HMV_HEAVY',
      licenseExpiry: new Date('2027-10-14'),
      status: 'ON_LEAVE',
      rating: 4.74,
      totalDeliveries: 175,
      onTimeRatePercent: 94.5,
      emergencyContact: 'Meena Patil (+91 98900 66559)',
    },
    {
      code: 'DRV-110',
      firstName: 'Kavita',
      lastName: 'Sharma',
      email: 'kavita.s@fleetops.io',
      phone: '+91 98100 44332',
      licenseNumber: 'DL-DL-2022-0022019',
      licenseClass: 'LMV_TRANSPORT',
      licenseExpiry: new Date('2028-07-08'),
      status: 'AVAILABLE',
      rating: 4.90,
      totalDeliveries: 110,
      onTimeRatePercent: 97.8,
      emergencyContact: 'Rohit Sharma (+91 98100 44339)',
    },
  ];

  const createdDrivers: any[] = [];
  for (const d of driverData) {
    const driver = await prisma.driver.create({ data: d });
    createdDrivers.push(driver);
  }
  console.log(`🚚 Created ${createdDrivers.length} Drivers.`);

  // 4. Create Commercial Vehicles
  const vehicleData = [
    {
      code: 'VEH-401',
      vin: 'MAT49201948KL0192',
      make: 'Tata Motors',
      model: 'Prima 5530.S Tractor Trailer',
      year: 2023,
      licensePlate: 'MH-04-AB-4920',
      type: 'SEMI_TRAILER',
      status: 'IN_TRANSIT',
      maxPayloadKg: 38000,
      maxVolumeM3: 98.5,
      fuelType: 'DIESEL',
      currentFuelPercent: 82.5,
      currentMileageKm: 142850,
      currentLat: 19.1136,
      currentLng: 73.0112,
      lastServiceDate: new Date('2026-06-15'),
      nextServiceDueKm: 155000,
      assignedDriverId: createdDrivers[0].id,
      notes: 'Equipped with AIS-140 GPS telematics, air brakes, FASTag enabled.',
    },
    {
      code: 'VEH-402',
      vin: 'MAL88120391NJ3891',
      make: 'Ashok Leyland',
      model: 'AVTR 4220 HG 6x2 Multi-Axle',
      year: 2024,
      licensePlate: 'MH-46-CL-8812',
      type: 'SEMI_TRAILER',
      status: 'IN_TRANSIT',
      maxPayloadKg: 32000,
      maxVolumeM3: 102.0,
      fuelType: 'DIESEL',
      currentFuelPercent: 68.0,
      currentMileageKm: 88400,
      currentLat: 18.9712,
      currentLng: 73.0245,
      lastServiceDate: new Date('2026-07-10'),
      nextServiceDueKm: 100000,
      assignedDriverId: createdDrivers[1].id,
      notes: 'i-Gen6 BS6 engine, dual fuel tanks, National Permit valid.',
    },
    {
      code: 'VEH-403',
      vin: 'MBB74190283PA8102',
      make: 'BharatBenz',
      model: '3528R Heavy Duty Hauler',
      year: 2023,
      licensePlate: 'DL-1A-AA-7419',
      type: 'SEMI_TRAILER',
      status: 'IN_TRANSIT',
      maxPayloadKg: 28500,
      maxVolumeM3: 95.0,
      fuelType: 'DIESEL',
      currentFuelPercent: 74.0,
      currentMileageKm: 119200,
      currentLat: 19.2183,
      currentLng: 72.9781,
      lastServiceDate: new Date('2026-05-20'),
      nextServiceDueKm: 130000,
      assignedDriverId: createdDrivers[2].id,
      notes: 'Pneumatic air suspension, Truckonnect fleet telematics.',
    },
    {
      code: 'VEH-404',
      vin: 'MTS61029384NY9014',
      make: 'Tata Motors',
      model: 'Signa 4825.TK Coldliner Reefer',
      year: 2024,
      licensePlate: 'GJ-06-TR-6102',
      type: 'REEFER_TRUCK',
      status: 'IN_TRANSIT',
      maxPayloadKg: 24000,
      maxVolumeM3: 88.0,
      fuelType: 'DIESEL',
      currentFuelPercent: 61.5,
      currentMileageKm: 64100,
      currentLat: 19.0760,
      currentLng: 72.8777,
      lastServiceDate: new Date('2026-08-01'),
      nextServiceDueKm: 80000,
      assignedDriverId: createdDrivers[3].id,
      notes: 'Multi-temperature refrigeration unit certified for pharmaceuticals and dairy.',
    },
    {
      code: 'EV-401',
      vin: 'MMZ30219485NN3192',
      make: 'Mahindra',
      model: 'Zor Grand EV Express',
      year: 2024,
      licensePlate: 'KA-01-EV-3021',
      type: 'EV_VAN',
      status: 'ACTIVE',
      maxPayloadKg: 2200,
      maxVolumeM3: 18.7,
      fuelType: 'ELECTRIC',
      currentFuelPercent: 91.0,
      currentMileageKm: 28400,
      currentLat: 19.2967,
      currentLng: 73.0631,
      lastServiceDate: new Date('2026-07-28'),
      nextServiceDueKm: 45000,
      assignedDriverId: null,
      notes: 'Zero emissions, 140-km city corridor range, regenerative braking.',
    },
    {
      code: 'EV-402',
      vin: 'MTA41092830PR8821',
      make: 'Tata Motors',
      model: 'Ace EV Ultra Express',
      year: 2024,
      licensePlate: 'KA-05-EV-4109',
      type: 'EV_VAN',
      status: 'ACTIVE',
      maxPayloadKg: 1800,
      maxVolumeM3: 15.0,
      fuelType: 'ELECTRIC',
      currentFuelPercent: 84.0,
      currentMileageKm: 31200,
      currentLat: 19.2282,
      currentLng: 73.0776,
      lastServiceDate: new Date('2026-06-30'),
      nextServiceDueKm: 50000,
      assignedDriverId: null,
      notes: 'EVoGen powertrain, fast-charging enabled, metro delivery.',
    },
    {
      code: 'BX-201',
      vin: 'MEP78210394MDC781',
      make: 'Eicher',
      model: 'Pro 6028 Medium Duty Box',
      year: 2023,
      licensePlate: 'MH-12-BX-7821',
      type: 'BOX_TRUCK',
      status: 'ACTIVE',
      maxPayloadKg: 16500,
      maxVolumeM3: 45.0,
      fuelType: 'DIESEL',
      currentFuelPercent: 78.0,
      currentMileageKm: 76500,
      currentLat: 19.0484,
      currentLng: 72.8857,
      lastServiceDate: new Date('2026-07-14'),
      nextServiceDueKm: 90000,
      assignedDriverId: null,
      notes: 'Hydraulic tail-lift 2-tonne capacity, corrugated cargo container.',
    },
    {
      code: 'BX-202',
      vin: 'MAL55091823LCR991',
      make: 'Ashok Leyland',
      model: 'Ecomet 1615 HE Container',
      year: 2022,
      licensePlate: 'TN-09-BX-5509',
      type: 'BOX_TRUCK',
      status: 'MAINTENANCE',
      maxPayloadKg: 11200,
      maxVolumeM3: 38.0,
      fuelType: 'DIESEL',
      currentFuelPercent: 45.0,
      currentMileageKm: 112000,
      currentLat: 19.2967,
      currentLng: 73.0631,
      lastServiceDate: new Date('2026-08-25'),
      nextServiceDueKm: 115000,
      assignedDriverId: null,
      notes: 'In central maintenance bay for scheduled brake liner & drum overhaul.',
    },
    {
      code: 'VN-101',
      vin: 'MMB90810294MP0192',
      make: 'Mahindra',
      model: 'Bolero Maxi Truck Plus',
      year: 2023,
      licensePlate: 'MH-02-VN-9081',
      type: 'SPRINTER_VAN',
      status: 'ACTIVE',
      maxPayloadKg: 1750,
      maxVolumeM3: 14.5,
      fuelType: 'DIESEL',
      currentFuelPercent: 94.0,
      currentMileageKm: 42100,
      currentLat: 19.1028,
      currentLng: 72.8870,
      lastServiceDate: new Date('2026-08-10'),
      nextServiceDueKm: 60000,
      assignedDriverId: null,
      notes: 'Intra-city rapid dispatch express parcel carrier.',
    },
    {
      code: 'VN-102',
      vin: 'MFU33190284NE6710',
      make: 'Force Motors',
      model: 'Urbania Express High Roof',
      year: 2022,
      licensePlate: 'HR-26-VN-3319',
      type: 'SPRINTER_VAN',
      status: 'IDLE',
      maxPayloadKg: 2200,
      maxVolumeM3: 16.2,
      fuelType: 'CNG',
      currentFuelPercent: 88.0,
      currentMileageKm: 59300,
      currentLat: 19.2967,
      currentLng: 73.0631,
      lastServiceDate: new Date('2026-07-02'),
      nextServiceDueKm: 70000,
      assignedDriverId: null,
      notes: 'Stationed at Bhiwandi Central Depot ready for overflow dispatch.',
    },
    {
      code: 'VEH-405',
      vin: 'MTU88901928PN5520',
      make: 'Tata Motors',
      model: 'Ultra T.7 EV Heavy Hauler',
      year: 2024,
      licensePlate: 'DL-1A-EV-8890',
      type: 'SEMI_TRAILER',
      status: 'ACTIVE',
      maxPayloadKg: 26000,
      maxVolumeM3: 94.0,
      fuelType: 'ELECTRIC',
      currentFuelPercent: 96.0,
      currentMileageKm: 18200,
      currentLat: 19.2967,
      currentLng: 73.0631,
      lastServiceDate: new Date('2026-08-12'),
      nextServiceDueKm: 35000,
      assignedDriverId: null,
      notes: 'Heavy electric tractor trailer for port container drayage.',
    },
    {
      code: 'BX-203',
      vin: 'MEP22190182NH7781',
      make: 'Eicher',
      model: 'Pro 3019 Heavy Freight Box',
      year: 2023,
      licensePlate: 'MH-04-BX-2219',
      type: 'BOX_TRUCK',
      status: 'IDLE',
      maxPayloadKg: 14500,
      maxVolumeM3: 48.0,
      fuelType: 'DIESEL',
      currentFuelPercent: 72.0,
      currentMileageKm: 84000,
      currentLat: 19.2967,
      currentLng: 73.0631,
      lastServiceDate: new Date('2026-06-25'),
      nextServiceDueKm: 95000,
      assignedDriverId: null,
      notes: 'E494 CRS engine with fuel coaching telematics.',
    },
  ];

  const createdVehicles: any[] = [];
  for (const v of vehicleData) {
    const vehicle = await prisma.vehicle.create({ data: v });
    createdVehicles.push(vehicle);
  }
  console.log(`🚛 Created ${createdVehicles.length} Vehicles.`);

  // 5. Create Maintenance Logs
  const maintenanceLogs = [
    {
      vehicleId: createdVehicles[7].id, // BX-202
      serviceType: 'BRAKE_INSPECTION',
      description: 'Replaced front and rear air brake drums, liners, and automatic slack adjusters.',
      cost: 18500.00,
      odometerKm: 112000,
      serviceDate: new Date('2026-08-25'),
      performedBy: 'Ashok Leyland Authorized Service Bay',
      status: 'IN_PROGRESS',
    },
    {
      vehicleId: createdVehicles[0].id, // VEH-401
      serviceType: 'OIL_CHANGE',
      description: 'Synthetic engine oil, oil filters, and AdBlue / DEF replenishment.',
      cost: 6200.00,
      odometerKm: 140000,
      serviceDate: new Date('2026-06-15'),
      performedBy: 'Tata Motors Commercial Workshop',
      status: 'COMPLETED',
    },
    {
      vehicleId: createdVehicles[1].id, // VEH-402
      serviceType: 'TIRE_ROTATION',
      description: 'Mounted 4 new radial steer tires and aligned front tandem axle.',
      cost: 24000.00,
      odometerKm: 85000,
      serviceDate: new Date('2026-07-10'),
      performedBy: 'Apollo Commercial Tire Center, Bhiwandi',
      status: 'COMPLETED',
    },
    {
      vehicleId: createdVehicles[3].id, // VEH-404 Reefer
      serviceType: 'ENGINE_REPAIR',
      description: 'Refrigeration unit compressor calibration and R404A refrigerant recharge.',
      cost: 14500.00,
      odometerKm: 60000,
      serviceDate: new Date('2026-08-01'),
      performedBy: 'Carrier Transicold Service Center',
      status: 'COMPLETED',
    },
    {
      vehicleId: createdVehicles[4].id, // EV-401
      serviceType: 'BATTERY_CHECK',
      description: 'High-voltage battery telematics diagnostic, BMS firmware update, and coolant loop flush.',
      cost: 4800.00,
      odometerKm: 25000,
      serviceDate: new Date('2026-07-28'),
      performedBy: 'Mahindra EV Commercial Support',
      status: 'COMPLETED',
    },
  ];

  for (const m of maintenanceLogs) {
    await prisma.maintenanceLog.create({ data: m });
  }
  console.log(`🔧 Created ${maintenanceLogs.length} Maintenance Logs.`);

  // 6. Create Realistic Orders
  const orderData = [
    // In-Transit Orders
    {
      orderNumber: 'ORD-2026-9041',
      customerName: 'Reliance Retail Logistics Ltd',
      customerEmail: 'supplychain@relianceretail.com',
      customerPhone: '+91 98201 92041',
      customerAddress: 'Reliance Corporate Park, Thane-Belapur Rd, Navi Mumbai 400701',
      pickupAddress: 'JNPT Port Terminal Container Yard, Nhava Sheva, Navi Mumbai 400707',
      pickupLat: 18.9496,
      pickupLng: 72.9515,
      deliveryAddress: 'Bhiwandi Mega Fulfillment Hub, Mankoli Naka, Bhiwandi 421302',
      deliveryLat: 19.2967,
      deliveryLng: 73.0631,
      weightKg: 24500,
      volumeM3: 72.0,
      cargoType: 'GENERAL_FREIGHT',
      priority: 'HIGH',
      status: 'IN_TRANSIT',
      deliveryFee: 18500.00,
      notes: 'Imported consumer electronics containers; GPS e-lock secured.',
    },
    {
      orderNumber: 'ORD-2026-9042',
      customerName: 'Sun Pharma Distribution',
      customerEmail: 'coldchain@sunpharma.com',
      customerPhone: '+91 98202 84311',
      customerAddress: 'Sun House, CTS No. 201 B/1, Western Express Hwy, Goregaon, Mumbai 400063',
      pickupAddress: 'Bhiwandi Central Pharma Cold Hub, Sector 12, Thane 421302',
      pickupLat: 19.2967,
      pickupLng: 73.0631,
      deliveryAddress: 'Apollo Hospitals Central Medical Depot, CBD Belapur, Navi Mumbai 400614',
      deliveryLat: 19.0178,
      deliveryLng: 73.0410,
      weightKg: 4200,
      volumeM3: 16.5,
      cargoType: 'COLD_CHAIN',
      priority: 'URGENT',
      status: 'IN_TRANSIT',
      deliveryFee: 24000.00,
      notes: 'Vaccines and temperature-sensitive biologicals. Maintain -20°C strictly.',
    },
    {
      orderNumber: 'ORD-2026-9043',
      customerName: 'Tata Consultancy Systems Infrastructure',
      customerEmail: 'dcops@tcs.com',
      customerPhone: '+91 98203 33290',
      customerAddress: 'TCS Olympus, Hiranandani Estate, Thane, Maharashtra 400607',
      pickupAddress: 'Vikhroli Intermodal Tech Depot, LBS Marg, Vikhroli, Mumbai 400079',
      pickupLat: 19.1112,
      pickupLng: 72.9281,
      deliveryAddress: 'Airoli Mindspace Data Center Zone, Navi Mumbai 400708',
      deliveryLat: 19.1554,
      deliveryLng: 72.9935,
      weightKg: 8900,
      volumeM3: 28.0,
      cargoType: 'HIGH_VALUE',
      priority: 'HIGH',
      status: 'IN_TRANSIT',
      deliveryFee: 21000.00,
      notes: 'High-density GPU AI server racks; air suspension transport required.',
    },
    {
      orderNumber: 'ORD-2026-9044',
      customerName: 'Amul Dairy Cooperative Federation',
      customerEmail: 'logistics@amul.coop',
      customerPhone: '+91 98204 77654',
      customerAddress: 'Amul Dairy Plant, GIDC Anand, Gujarat 388001',
      pickupAddress: 'Vasai Agro Distribution Center, Vasai East, Palghar 401208',
      pickupLat: 19.3820,
      pickupLng: 72.8410,
      deliveryAddress: 'APMC Wholesale Market Terminal, Vashi, Navi Mumbai 400703',
      deliveryLat: 19.0760,
      deliveryLng: 72.9980,
      weightKg: 18200,
      volumeM3: 65.0,
      cargoType: 'PERISHABLE',
      priority: 'STANDARD',
      status: 'IN_TRANSIT',
      deliveryFee: 19500.00,
      notes: 'Dairy products and fresh milk crates; morning distribution window.',
    },
    // Completed Orders
    {
      orderNumber: 'ORD-2026-8801',
      customerName: 'Pidilite Chemical Logistics',
      customerEmail: 'dispatch@pidilite.com',
      customerPhone: '+91 98205 60199',
      customerAddress: 'Ramkrishna Mandir Rd, Andheri East, Mumbai 400059',
      pickupAddress: 'Taloja MIDC Industrial Chemical Bay, Taloja, Raigad 410208',
      pickupLat: 19.0687,
      pickupLng: 73.1143,
      deliveryAddress: 'Chakan Industrial Zone Phase 2, Pune, Maharashtra 410501',
      deliveryLat: 18.7606,
      deliveryLng: 73.8636,
      weightKg: 16000,
      volumeM3: 35.0,
      cargoType: 'HAZMAT',
      priority: 'HIGH',
      status: 'DELIVERED',
      deliveryFee: 28000.00,
      notes: 'Industrial polymers and adhesives; Hazmat emergency response sheet verified.',
    },
    {
      orderNumber: 'ORD-2026-8802',
      customerName: 'Flipkart Supply Chain Operations',
      customerEmail: 'inbound.mumbai@flipkart.com',
      customerPhone: '+91 98206 44388',
      customerAddress: 'Flipkart Regional Sortation Center, Bhiwandi 421302',
      pickupAddress: 'JNPT Port Container Berth 4, Nhava Sheva 400707',
      pickupLat: 18.9496,
      pickupLng: 72.9515,
      deliveryAddress: 'Flipkart Hub, Kopergaon Logistics Corridor, Thane 421302',
      deliveryLat: 19.2718,
      deliveryLng: 73.0452,
      weightKg: 12800,
      volumeM3: 42.0,
      cargoType: 'GENERAL_FREIGHT',
      priority: 'STANDARD',
      status: 'DELIVERED',
      deliveryFee: 16000.00,
      notes: 'Consumer goods standard pallets; digital POD signed.',
    },
    {
      orderNumber: 'ORD-2026-8803',
      customerName: 'JSW Steel Industrial Goods',
      customerEmail: 'logistics@jsw.in',
      customerPhone: '+91 98207 22044',
      customerAddress: 'JSW Centre, Bandra Kurla Complex, Mumbai 400051',
      pickupAddress: 'Dolvi Steel Plant Depot, Raigad, Maharashtra 402107',
      pickupLat: 18.7056,
      pickupLng: 73.0402,
      deliveryAddress: 'Sanand Industrial Manufacturing Hub, Ahmedabad, Gujarat 382110',
      deliveryLat: 22.9871,
      deliveryLng: 72.3829,
      weightKg: 32500,
      volumeM3: 45.0,
      cargoType: 'GENERAL_FREIGHT',
      priority: 'STANDARD',
      status: 'DELIVERED',
      deliveryFee: 45000.00,
      notes: 'Structural steel coils and TMT bars; heavy-duty tarpaulin tied.',
    },
    // Pending Orders (ready to assign)
    {
      orderNumber: 'ORD-2026-9050',
      customerName: 'Adani Solar Technologies',
      customerEmail: 'solarlogistics@adani.com',
      customerPhone: '+91 98208 91948',
      customerAddress: 'Adani Corporate House, Shantigram, Ahmedabad 382421',
      pickupAddress: 'Mundra Port Container Logistics Yard, Mundra, Gujarat 370421',
      pickupLat: 22.8392,
      pickupLng: 69.7145,
      deliveryAddress: 'Shirdi Solar Farm Substation Phase 3, Ahmednagar, Maharashtra 423109',
      deliveryLat: 19.7681,
      deliveryLng: 74.4841,
      weightKg: 15200,
      volumeM3: 48.0,
      cargoType: 'FRAGILE',
      priority: 'HIGH',
      status: 'PENDING',
      deliveryFee: 32000.00,
      notes: 'Photovoltaic bifacial solar panels. Glass crates; shock sensors enabled.',
    },
    {
      orderNumber: 'ORD-2026-9051',
      customerName: 'Blue Tokai Coffee Roasters',
      customerEmail: 'greenbeans@bluetokaicoffee.com',
      customerPhone: '+91 98209 30488',
      customerAddress: 'Laxmi Mills Compound, Shakti Mills Ln, Mahalaxmi, Mumbai 400011',
      pickupAddress: 'Chikmagalur Coffee Estate Depot, Karnataka 577101',
      pickupLat: 13.3181,
      pickupLng: 75.7725,
      deliveryAddress: 'Mahalaxmi Roastery, Shakti Mills Ln, Mumbai 400011',
      deliveryLat: 18.9833,
      deliveryLng: 72.8268,
      weightKg: 4950,
      volumeM3: 14.5,
      cargoType: 'GENERAL_FREIGHT',
      priority: 'STANDARD',
      status: 'PENDING',
      deliveryFee: 12500.00,
      notes: 'Specialty green Arabica coffee jute bags; moisture-protected.',
    },
    {
      orderNumber: 'ORD-2026-9052',
      customerName: 'Mahyco Agro Produce Cooperative',
      customerEmail: 'sales@mahyco.com',
      customerPhone: '+91 98210 67034',
      customerAddress: 'Jalna Agro Center, Maharashtra 431203',
      pickupAddress: 'Nashik Onion & Grape Produce Hub, Nashik 422001',
      pickupLat: 19.9975,
      pickupLng: 73.7898,
      deliveryAddress: 'Vashi APMC Fruit & Vegetable Market, Navi Mumbai 400703',
      deliveryLat: 19.0760,
      deliveryLng: 72.9980,
      weightKg: 14400,
      volumeM3: 45.0,
      cargoType: 'PERISHABLE',
      priority: 'HIGH',
      status: 'PENDING',
      deliveryFee: 18000.00,
      notes: 'Export quality grapes and fresh produce crates.',
    },
  ];

  const createdOrders: any[] = [];
  for (const o of orderData) {
    const order = await prisma.order.create({ data: o });
    createdOrders.push(order);
  }
  console.log(`📦 Created ${createdOrders.length} Orders.`);

  // 7. Create Deliveries and Timeline Events
  // Delivery 1: In-Transit (ORD-2026-9041)
  const del1 = await prisma.delivery.create({
    data: {
      trackingNumber: 'TRK-882910',
      orderId: createdOrders[0].id,
      driverId: createdDrivers[0].id,
      vehicleId: createdVehicles[0].id,
      status: 'IN_TRANSIT',
      priority: 'HIGH',
      pickupScheduledAt: new Date(Date.now() - 3 * 3600 * 1000),
      pickupActualAt: new Date(Date.now() - 2.5 * 3600 * 1000),
      deliveryEstimatedAt: new Date(Date.now() + 1.2 * 3600 * 1000),
      currentLat: 19.1136,
      currentLng: 73.0112,
      progressPercent: 58.0,
      routeDistanceKm: 64.2,
      routeDurationMin: 110,
      notes: 'Navigating Thane-Belapur freight corridor; traffic normal through Airoli bypass.',
    },
  });

  await prisma.deliveryTimelineEvent.createMany({
    data: [
      {
        deliveryId: del1.id,
        status: 'ORDER_PLACED',
        title: 'Order Placed & Registered',
        description: 'Customer order confirmed and manifest generated for Reliance Retail Logistics.',
        locationName: createdOrders[0].pickupAddress,
        lat: 18.9496,
        lng: 72.9515,
        recordedAt: new Date(Date.now() - 4 * 3600 * 1000),
        recordedBy: 'System',
      },
      {
        deliveryId: del1.id,
        status: 'DISPATCHED',
        title: 'Dispatched to Fleet',
        description: `Assigned to Driver Vikram Singh with Tata Prima 5530.S (MH-04-AB-4920).`,
        locationName: 'Bhiwandi Central Dispatch Control',
        lat: 19.2967,
        lng: 73.0631,
        recordedAt: new Date(Date.now() - 3.2 * 3600 * 1000),
        recordedBy: 'Priya Nair (Dispatcher)',
      },
      {
        deliveryId: del1.id,
        status: 'PICKED_UP',
        title: 'Cargo Loaded & Gate Pass Cleared',
        description: '24,500 kg electronics containers secured. JNPT port outbound gate passed.',
        locationName: createdOrders[0].pickupAddress,
        lat: 18.9496,
        lng: 72.9515,
        recordedAt: new Date(Date.now() - 2.5 * 3600 * 1000),
        recordedBy: 'Vikram Singh (Driver)',
      },
      {
        deliveryId: del1.id,
        status: 'IN_TRANSIT',
        title: 'In Transit on Freight Corridor',
        description: 'Crossing Airoli Bridge freight bypass towards Thane-Bhiwandi logistics corridor.',
        locationName: 'Airoli Expressway Corridor',
        lat: 19.1554,
        lng: 72.9935,
        recordedAt: new Date(Date.now() - 1 * 3600 * 1000),
        recordedBy: 'FASTag Telematics Engine',
      },
    ],
  });

  // Delivery 2: Cold Chain In-Transit (ORD-2026-9042)
  const del2 = await prisma.delivery.create({
    data: {
      trackingNumber: 'TRK-904128',
      orderId: createdOrders[1].id,
      driverId: createdDrivers[3].id, // Manoj Yadav
      vehicleId: createdVehicles[3].id, // VEH-404 Reefer
      status: 'OUT_FOR_DELIVERY',
      priority: 'URGENT',
      pickupScheduledAt: new Date(Date.now() - 2 * 3600 * 1000),
      pickupActualAt: new Date(Date.now() - 1.8 * 3600 * 1000),
      deliveryEstimatedAt: new Date(Date.now() + 25 * 60 * 1000),
      currentLat: 19.0350,
      currentLng: 73.0320,
      progressPercent: 88.0,
      routeDistanceKm: 42.5,
      routeDurationMin: 65,
      notes: 'Cold chain verified at -18.4°C. Approaching Apollo Hospitals Belapur receiving dock.',
    },
  });

  await prisma.deliveryTimelineEvent.createMany({
    data: [
      {
        deliveryId: del2.id,
        status: 'ORDER_PLACED',
        title: 'Cold Chain Manifest Created',
        description: 'Urgent medical pharmaceutical cold-chain priority dispatch for Sun Pharma.',
        locationName: createdOrders[1].pickupAddress,
        lat: 19.2967,
        lng: 73.0631,
        recordedAt: new Date(Date.now() - 3 * 3600 * 1000),
        recordedBy: 'System',
      },
      {
        deliveryId: del2.id,
        status: 'PICKED_UP',
        title: 'Reefer Loaded & Pre-Cooled',
        description: 'Cargo temperature logged at -18.4°C. Verified by QA inspector at Bhiwandi Cold Hub.',
        locationName: createdOrders[1].pickupAddress,
        lat: 19.2967,
        lng: 73.0631,
        recordedAt: new Date(Date.now() - 1.8 * 3600 * 1000),
        recordedBy: 'Manoj Yadav (Driver)',
      },
      {
        deliveryId: del2.id,
        status: 'IN_TRANSIT',
        title: 'In Transit via Palm Beach Corridor',
        description: 'Navi Mumbai transit corridor entered. Telemetry continuous.',
        locationName: 'Palm Beach Road Corridor',
        lat: 19.0580,
        lng: 73.0150,
        recordedAt: new Date(Date.now() - 45 * 60 * 1000),
        recordedBy: 'AIS-140 GPS Engine',
      },
      {
        deliveryId: del2.id,
        status: 'OUT_FOR_DELIVERY',
        title: 'Out for Final Mile Delivery',
        description: 'Within 2 km of Apollo Hospitals Medical Receiving Dock 2.',
        locationName: 'CBD Belapur Receiving Zone',
        lat: 19.0350,
        lng: 73.0320,
        recordedAt: new Date(Date.now() - 10 * 60 * 1000),
        recordedBy: 'Manoj Yadav (Driver)',
      },
    ],
  });

  // Delivery 3: Completed Delivery (ORD-2026-8801)
  const del3 = await prisma.delivery.create({
    data: {
      trackingNumber: 'TRK-771920',
      orderId: createdOrders[4].id,
      driverId: createdDrivers[1].id,
      vehicleId: createdVehicles[1].id,
      status: 'DELIVERED',
      priority: 'HIGH',
      pickupScheduledAt: new Date(Date.now() - 28 * 3600 * 1000),
      pickupActualAt: new Date(Date.now() - 27.5 * 3600 * 1000),
      deliveryEstimatedAt: new Date(Date.now() - 24 * 3600 * 1000),
      deliveryActualAt: new Date(Date.now() - 24.2 * 3600 * 1000), // on time!
      currentLat: 18.7606,
      currentLng: 73.8636,
      progressPercent: 100.0,
      routeDistanceKm: 128.4,
      routeDurationMin: 180,
      recipientSignature: 'Signed by: Santosh Kadam (Chakan Plant Mgr)',
      notes: 'Delivered in perfect condition via Mumbai-Pune Expressway without exceptions.',
    },
  });

  await prisma.deliveryTimelineEvent.createMany({
    data: [
      {
        deliveryId: del3.id,
        status: 'DISPATCHED',
        title: 'Dispatched to Fleet',
        description: 'Hazmat compliant Ashok Leyland multi-axle vehicle assigned.',
        locationName: 'Taloja Chemical Hub',
        lat: 19.0687,
        lng: 73.1143,
        recordedAt: new Date(Date.now() - 28 * 3600 * 1000),
        recordedBy: 'Priya Nair',
      },
      {
        deliveryId: del3.id,
        status: 'PICKED_UP',
        title: 'Hazmat Inspected & Loaded',
        description: 'Placards affixed. Driver verified TREMCARD and emergency response kit.',
        locationName: 'Taloja Industrial Bay 4',
        lat: 19.0687,
        lng: 73.1143,
        recordedAt: new Date(Date.now() - 27.5 * 3600 * 1000),
        recordedBy: 'Ramesh Gurjar (Driver)',
      },
      {
        deliveryId: del3.id,
        status: 'IN_TRANSIT',
        title: 'Transit via Mumbai-Pune Expressway',
        description: 'Passed Khalapur Toll Plaza. Telemetry tracking green.',
        locationName: 'Mumbai-Pune Expressway',
        lat: 18.8200,
        lng: 73.3500,
        recordedAt: new Date(Date.now() - 26 * 3600 * 1000),
        recordedBy: 'System',
      },
      {
        deliveryId: del3.id,
        status: 'DELIVERED',
        title: 'Delivery Completed',
        description: 'Offloaded at Chakan MIDC receiving bay dock 1. Digital POD signed.',
        locationName: createdOrders[4].deliveryAddress,
        lat: 18.7606,
        lng: 73.8636,
        recordedAt: new Date(Date.now() - 24.2 * 3600 * 1000),
        recordedBy: 'Ramesh Gurjar (Driver)',
      },
    ],
  });

  console.log('🏁 Created Deliveries & Timeline Events.');

  // 8. Create System Settings
  const defaultSettings = [
    { key: 'company_name', value: 'LogisticsOne India Pvt Ltd', category: 'COMPANY', description: 'Organization name displayed across documents and dispatch manifest' },
    { key: 'company_code', value: 'L1-IND-01', category: 'COMPANY', description: 'Central dispatch operations identifier' },
    { key: 'depot_address', value: 'Bhiwandi Central Logistics Hub, Sector 18, Thane, Maharashtra 421302', category: 'COMPANY', description: 'Primary hub depot address' },
    { key: 'depot_lat', value: '19.2967', category: 'COMPANY', description: 'Primary depot latitude coordinates' },
    { key: 'depot_lng', value: '73.0631', category: 'COMPANY', description: 'Primary depot longitude coordinates' },
    { key: 'auto_dispatch_enabled', value: 'true', category: 'DISPATCH', description: 'Enable intelligent algorithm auto-matching for incoming orders' },
    { key: 'max_driver_hours_per_day', value: '10', category: 'DISPATCH', description: 'Motor Vehicles Act limit for active driver hours per 24h cycle' },
    { key: 'delay_threshold_minutes', value: '15', category: 'ALERTS', description: 'Trigger priority warning if ETA exceeds scheduled time by minutes' },
    { key: 'speed_alert_kmh', value: '80', category: 'ALERTS', description: 'Commercial vehicle speed limit trigger for highway corridors' },
    { key: 'low_fuel_alert_percent', value: '15', category: 'ALERTS', description: 'Trigger refueling dispatch notice when tank drops below threshold' },
    { key: 'notify_email_dispatch', value: 'true', category: 'NOTIFICATIONS', description: 'Send real-time alerts on urgent order assignment' },
    { key: 'notify_sms_customer', value: 'true', category: 'NOTIFICATIONS', description: 'Send automated SMS tracking link to customers upon dispatch' },
    { key: 'units_system', value: 'METRIC', category: 'GENERAL', description: 'Default measurement unit system (METRIC / IMPERIAL)' },
  ];

  for (const s of defaultSettings) {
    await prisma.systemSetting.create({ data: s });
  }

  // 9. Initial Audit Logs
  await prisma.auditLog.createMany({
    data: [
      {
        userId: adminUser.id,
        userName: adminUser.name,
        action: 'SYSTEM_INIT',
        entityType: 'USER',
        entityId: adminUser.id,
        details: 'Initial system initialization, Indian logistics compliance verified, and fleet baseline seeded.',
        ipAddress: '127.0.0.1',
      },
      {
        userId: dispatcherUser.id,
        userName: dispatcherUser.name,
        action: 'DISPATCH',
        entityType: 'DELIVERY',
        entityId: del1.id,
        details: 'Dispatched TRK-882910 with High priority route optimization on JNPT corridor.',
        ipAddress: '192.168.1.45',
      },
      {
        userId: opsUser.id,
        userName: opsUser.name,
        action: 'MAINTENANCE_SCHEDULE',
        entityType: 'VEHICLE',
        entityId: createdVehicles[7].id,
        details: 'Scheduled brake overhaul for Ashok Leyland Ecomet (TN-09-BX-5509).',
        ipAddress: '192.168.1.52',
      },
    ],
  });

  console.log('✅ Seed completed successfully with Indian logistics records!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
